Repository koreanAir1/Frontend, pull requests merged in 2025-05, with the labels that each got.

#6 feat: 추천 디자인
  src/pages/recommend/index.jsx
Labels: 💥feature

#11 fix: 디자인 수정
  src/pages/details/index.jsx
  src/pages/home/index.jsx
  src/pages/recommend/index.jsx
Labels: 😎refactor

#13 feat: api 연동
  public/assets/images/defaultImage.png
  src/api/common_menu/index.js
  src/api/feedback/index.js
  src/api/index.js
  src/api/menu/index.js
  src/api/recommend/index.js
  src/components/card/index.jsx
  src/main.jsx
  src/pages/details/index.jsx
  src/pages/home/index.jsx
  src/pages/recommend/index.jsx
  src/stores/atom/index.js
Labels: 💥feature, 😎refactor
